---
suid_sgid_permissions: false
suid_sgid_blocklist:
  - 7z
  - aa-exec
  - ab
  - agetty
  - alpine
  - ansible-playbook
  - ansible-test
  - aoss
  - ar
  - aria2c
  - arj
  - arp
  - as
  - ascii85
  - ascii-xfr
  - ash
  - aspell
  - at
  - atobm
  - awk
  - aws
  - base32
  - base58
  - base64
  - basenc
  - basez
  - batcat
  - bc
  - bconsole
  - bpftrace
  - bridge
  - bsd-write
  - bundle
  - bundler
  - busctl
  - busybox
  - byebug
  - bzip2
  - c89
  - c99
  - cabal
  - cancel
  - capsh
  - cdist
  - certbot
  - chage
  - check_by_ssh
  - check_cups
  - check_log
  - check_memory
  - check_raid
  - check_ssl_cert
  - check_statusfile
  - chfn
  - chsh
  - cmp
  - cobc
  - column
  - comm
  - composer
  - cowsay
  - cowthink
  - cpan
  - cpio
  - cpulimit
  - crash
  - csh
  - csplit
  - csvtool
  - cupsfilter
  - dash
  - debugfs
  - dialog
  - dig
  - distcc
  - dmesg
  - dmidecode
  - dmsetup
  - dnf
  - docker
  - dos2unix
  - dosbox
  - dotnet
  - dstat
  - dvips
  - easy_install
  - eb
  - ed
  - efax
  - elvish
  - emacs
  - eqn
  - espeak
  - ex
  - exiftool
  - expand
  - expect
  - facter
  - finger
  - fish
  - flock
  - fmt
  - fold
  - fping
  - ftp
  - fusermount
  - gawk
  - gcloud
  - gcore
  - gdb
  - gem
  - genie
  - genisoimage
  - ghc
  - ghci
  - gimp
  - ginsh
  - grc
  - gtester
  - gzip
  - hd
  - head
  - hexdump
  - highlight
  - hping3
  - iconv
  - iftop
  - ionice
  - irb
  - ispell
  - jjs
  - joe
  - join
  - journalctl
  - jq
  - jrunscript
  - jtag
  - julia
  - knife
  - ksh
  - ksshell
  - ksu
  - kubectl
  - latex
  - latexmk
  - ldconfig
  - ld.so
  - logsave
  - look
  - lp
  - ltrace
  - lua
  - lualatex
  - luatex
  - lwp-download
  - lwp-request
  - mail
  - man
  - mawk
  - mksh
  - mksh-static
  - mlocate
  - mosquitto
  - msfconsole
  - msgattrib
  - msgcat
  - msgconv
  - msgfilter
  - msgmerge
  - msguniq
  - mtr
  - multitime
  - nasm
  - nawk
  - nc
  - ncftp
  - neofetch
  - newgrp
  - nft
  - nice
  - nl
  - nm
  - node
  - nohup
  - npm
  - nroff
  - nsenter
